### ISSUE TITLE
Criação de página sobre

### ISSUE THREAD

**Issue by jow182** [johnatanlopes/github-master#3]
Vocês poderiam criar uma página de sobre? Agradeço

**Comment by johnatanlopes** [comment]
Página em produção.

**Comment by jow182** [comment]
Obrigado, estou aguardando
________________________________
De: johnatanlopes <notifications@github.com>
Enviado: quinta-feira, 11 de janeiro de 2018 02:12
Para: johnatanlopes/github-master
Cc: jow182; Author
Assunto: Re: [johnatanlopes/github-master] Criação de página sobre (#3)


Página em produção.
